### ISSUE TITLE
Cannot paste world transforms into a scriptable objects V3 field

### ISSUE THREAD

**Issue by XXChester** [KybernetikGames/inspector-gadgets#2]
I can copy the world transform position with the provided buttons in the inspector but if I have a simple SO like this, you cannot paste the transform position into the field:
```
[CreateAssetMenu(menuName = "Scriptable Objects/Data/Target Action Data")]
public class TargetActionDataSO : ScriptableObject
{
    public Vector3 targetPosition;

}
```

1. Create the above script
2. Compile it
3. Right click -> Scriptable Objects -> Data -> Target Action Data
4. Copy a world transform from the inspector
5. Right click the Target Position field in the Target Action Data's SO inspector and note you cannot paste.

This was the whole reason I got this asset so I am quite disappointed that this doesn't work out of the box. Am I missing something or is this truly not a feature?

**Comment by KybernetikGames** [comment]
I just tested this and it seems to work fine:

![image](https://github.com/user-attachments/assets/45a8e859-9395-41aa-9a6f-925fc4a99126)

- Do you have the latest version of Inspector Gadgets (v8.0)?
- Do you only see the issue when copying world positions but not local?
- If you copy a position then paste into a text editor, does it give a properly formatted string that looks like `(x, y, z)`?

**Comment by XXChester** [comment]
I had the latest version of Lite and I believe that button in your screenshot had a "pro only" label on it so I guess it isn't available in the version I have. I never tried the local position, only world as that was specifically my use case. I believe I did copy it into word pad and it looked fine but I still couldn't paste it back in to the SO V3 field. Copying from the default GUI works as expected.

I removed the package already regardless, so feel free to close this.

**Comment by KybernetikGames** [comment]
[The Inspector Gadgets Copy/Paste/Reset context menu functions are actually Pro-Only features.](https://kybernetik.com.au/inspector-gadgets/docs/context-menu-functions/#reset-copy-and-paste)

So if you only have Lite, you'll only be seeing the functions that were added to Unity a few years ago which are a lot less flexible than the IG ones. If you Right Click the Transform Position and Copy it using their function, you'll get `Vector3(x,y,z)` on the clipboard rather than just `(x,y,z)` from the IG Copy button. And unfortunately their paste function only accepts their format.
